// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjvjgulfqmvjljiloyir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qdmpndWxmcW12amxqaWxveWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODY0OTQsImV4cCI6MjA1NjM2MjQ5NH0.VJEk9ZZoFlcreCwIHvpxY-o77KRCJ6EJJOAE4gfN7s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);